package youtube

import (
   "net/http"
   "testing"
)

var tests = []struct{
   id, desc string
   stream bool
}{
   {
      "ClYg-0-z_ds",
      "",
      false,
   }, {
      "XeojXq6ySs4",
      "Provided to YouTube by Epitaph\n\nSnowflake · Kate Bush\n\n" +
      "50 Words For Snow\n\n" +
      "℗ Noble & Brite Ltd. trading as Fish People, under exclusive license to Anti Inc.\n\n" +
      "Released on: 2011-11-22\n\nMusic  Publisher: Noble and Brite Ltd.\n" +
      "Composer  Lyricist: Kate Bush\n\nAuto-generated by YouTube.",
      true,
   },
}

func TestDesc(t *testing.T) {
   for _, test := range tests {
      v, e := NewVideo(test.id)
      if e != nil {
         t.Error(e)
      }
      if v.Description() != test.desc {
         t.Errorf("%+v\n", v)
      }
      if v.ViewCount() == 0 {
         t.Errorf("%+v\n", v)
      }
      if ! test.stream { continue }
      f, e := v.GetFormat(251)
      if e != nil {
         t.Error(e)
      }
      s, e := f.GetStream()
      if e != nil {
         t.Error(e)
      }
      println("Head", s)
      r, e := http.Head(s)
      if e != nil {
         t.Error(e)
      }
      if r.StatusCode != 200 {
         t.Error(r.StatusCode)
      }
   }
}
