package youtube
import "testing"

var tests = []struct {in, out string} {
   {
      "XeojXq6ySs4",
      "Provided to YouTube by Epitaph\n\nSnowflake · Kate Bush\n\n" +
      "50 Words For Snow\n\n" +
      "℗ Noble & Brite Ltd. trading as Fish People, under exclusive license to Anti Inc.\n\n" +
      "Released on: 2011-11-22\n\nMusic  Publisher: Noble and Brite Ltd.\n" +
      "Composer  Lyricist: Kate Bush\n\nAuto-generated by YouTube.",
   }, {
      "ClYg-0-z_ds",
      "",
   },
}

func TestInfo(t *testing.T) {
   for _, test := range tests {
      p, err := Info(test.in)
      if err != nil {
         t.Error(err)
      }
      if p.Description.SimpleText != test.out {
         t.Error(p)
      }
   }
}
