package youtube
import "testing"

const desc = "Provided to YouTube by Epitaph\n\nSnowflake · Kate Bush\n\n" +
"50 Words For Snow\n\n" +
"℗ Noble & Brite Ltd. trading as Fish People, under exclusive license to Anti Inc.\n\n" +
"Released on: 2011-11-22\n\nMusic  Publisher: Noble and Brite Ltd.\n" +
"Composer  Lyricist: Kate Bush\n\nAuto-generated by YouTube."

func TestContentLength(t *testing.T) {
   v, err := NewPlayer("eAzIAjTBGgU")
   if err != nil {
      t.Fatal(err)
   }
   if v.Description() != desc {
      t.Fatalf("%+v\n", v)
   }
   if v.ViewCount() == 0 {
      t.Fatalf("%+v\n", v)
   }
   // this should fail
   f, err := v.NewFormat(247)
   if err == nil {
      t.Fatal(f)
   }
}
