package youtube_test

import (
   "github.com/89z/mech/youtube"
   "testing"
)

const desc = "Provided to YouTube by Epitaph\n\nSnowflake · Kate Bush\n\n" +
"50 Words For Snow\n\n" +
"℗ Noble & Brite Ltd. trading as Fish People, under exclusive license to Anti Inc.\n\n" +
"Released on: 2011-11-22\n\nMusic  Publisher: Noble and Brite Ltd.\n" +
"Composer  Lyricist: Kate Bush\n\nAuto-generated by YouTube."

func TestMWeb(t *testing.T) {
   mw, err := youtube.NewMWeb("XeojXq6ySs4")
   if err != nil {
      t.Fatal(err)
   }
   if mw.PublishDate != "2020-11-05" {
      t.Fatalf("%+v\n", mw)
   }
   if mw.ShortDescription != desc {
      t.Fatalf("%+v\n", mw)
   }
   if mw.Title != "Snowflake" {
      t.Fatalf("%+v\n", mw)
   }
   if mw.ViewCount == 0 {
      t.Fatalf("%+v\n", mw)
   }
}
