package youtube_test

import (
   "github.com/89z/mech/youtube"
   "io"
   "testing"
)

const desc = "Provided to YouTube by Epitaph\n\nSnowflake · Kate Bush\n\n" +
"50 Words For Snow\n\n" +
"℗ Noble & Brite Ltd. trading as Fish People, under exclusive license to Anti Inc.\n\n" +
"Released on: 2011-11-22\n\nMusic  Publisher: Noble and Brite Ltd.\n" +
"Composer  Lyricist: Kate Bush\n\nAuto-generated by YouTube."

func TestGetVideoInfo(t *testing.T) {
   // Playback on other websites has been disabled by the video owner
   p, err := youtube.NewPlayer("MeJVWBSsPAY", youtube.Key, youtube.Android)
   if err != nil {
      t.Fatal(err)
   }
   f := p.AdaptiveFormats.Filter(func(f youtube.Format) bool {
      return f.Height == 0
   })
   if err := f[0].Write(io.Discard); err != nil {
      t.Fatal(err)
   }
}

func TestPlayer(t *testing.T) {
   p, err := youtube.NewPlayer("XeojXq6ySs4", youtube.Key, youtube.Mweb)
   if err != nil {
      t.Fatal(err)
   }
   if p.PublishDate != "2020-11-05" {
      t.Fatalf("%+v\n", p)
   }
   if p.ShortDescription != desc {
      t.Fatalf("%+v\n", p)
   }
   if p.Title != "Snowflake" {
      t.Fatalf("%+v\n", p)
   }
   if p.ViewCount == 0 {
      t.Fatalf("%+v\n", p)
   }
}
